version: '3'

services:
  db:
    image: redis:4.0
    volumes:
      - ./data/redis:/data  # 数据目录
      - ./conf/redis/redis.conf:/etc/redis/redis.conf  # 配置文件
    ports:
      - 6379:6379
    sysctls:
      - net.core.somaxconn=1024
    command: 
      bash -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf
      && redis-server /etc/redis/redis.conf --appendonly yes"
      
  apiserver:
    image: studiomj/jump-jump
    depends_on:
      - db
    ports:
      - 8080:8080
    entrypoint: ["./apiserver"]
    environment:
      - REDIS_DB=0
      - REDIS_HOST=db:6379
      - J2_API_ADDR=0.0.0.0:8080
      - SECRET_KEY=vinzst
      - GIN_MODE=release
      - ALLOWED_HOSTS=886600.xyz

  landingserver:
    image: studiomj/jump-jump
    depends_on:
      - db
    ports:
      - 8081:8081
    entrypoint: ["./landingserver"]
    environment:
      - REDIS_DB=0
      - REDIS_HOST=db:6379
      - J2_LANDING_ADDR=0.0.0.0:8081
      - GIN_MODE=release
      
   nginx:
     image: nginx:alpine
     ports:
      - 80:80
      - 8080:80
      - 443:443
     restart: always
     volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./wwwroot:/user/share/nginx/wwwroot
     
